//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public int ID_TIPO_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string TELEFONO { get; set; }
        public string RFC { get; set; }
        public string DIRECCION { get; set; }
        public string NUMERO_EXTERIOR { get; set; }
        public string NUMERO_INTERIOR { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string COLONIA { get; set; }
        public string TIPO_COLONIA { get; set; }
        public decimal LIMITE_CREDITO { get; set; }
        public int PLAZO { get; set; }
        public int CUENTA_CORTADA { get; set; }
        public string ESTADO { get; set; }
        public string EMAIL { get; set; }
        public string OBSERVACIONES { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
    
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
    }
}
