//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_VENTAEntities1 : DbContext
    {
        public BD_VENTAEntities1()
            : base("name=BD_VENTAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICULO> ARTICULO { get; set; }
        public DbSet<ESTATUS_ARTICULO> ESTATUS_ARTICULO { get; set; }
        public DbSet<IMPUESTO_ARTICULO> IMPUESTO_ARTICULO { get; set; }
        public DbSet<LINEA> LINEA { get; set; }
        public DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public DbSet<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        public DbSet<CODIGO_ARTICULO> CODIGO_ARTICULO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
    }
}
