//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO_FIJO { get; set; }
        public string CELULAR { get; set; }
        public string OBSERVACION { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
    }
}
