//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CLIENTE
    {
        public TIPO_CLIENTE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int ID_TIPO_CLIENTE { get; set; }
        public string NOMBEE_ { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_EMPLEADO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_EMPLEDO_ACTUALIZACION { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
